# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Relax-forme®
title2: Relax-
title3: forme®
slogan: Le massage enfin accessible à tous
description: > # this means to ignore newlines until "baseurl:"
    Relax-forme® est la marque déposée de la SAS Pandore, société créer en 2012,
    vente, location, installation et S.A.V de fauteuils de massage professionnels hauts de gamme
    de la marque française SUPRA, qui les conçoit depuis plus de 25 ans.
    Nous nous adressons aux particuliers ainsi qu’aux entreprises.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
site_username: relax-forme.fr
facebook_username: fauteuil.de.massage
email: info@relax-forme.fr
tel-fix: 09 52 50 81 14
tel-port: 06 78 97 06 09
adresse: 172 Bis rue du poirier rond 45000 ORLEANS

# Build settings
markdown: kramdown
